CREATE SCHEMA devLearn;
CREATE TABLE Administrador (
   ID INTEGER PRIMARY KEY NOT NULL UNIQUE,
   FOREIGN KEY (Usuario_ID) REFERENCES Usuario (ID),
);

CREATE TABLE Usuario (
   ID INTEGER PRIMARY KEY UNIQUE NOT NULL INCREMENT 1,
   Email VARCHAR(45) UNIQUE NOT NULL,
   Senha VARCHAR(45) NOT NULL,
   Nome VARCHAR(45),
   Sobrenome VARCHAR(45),
);

CREATE TABLE Perfil (
   ID INTEGER PRIMARY KEY UNIQUE NOT NULL,
   Foto VARCHAR(45) DEFAULT 'default',
   Descricao VARCHAR(45) DEFAULT 'Olá',
   Interesse INTEGER DEFAULT 0,
   Cursos_Salvos VARCHAR(45),
   FOREIGN KEY (Usuario_ID) REFERENCES Usuario (ID),
   FOREIGN KEY (Curso_ID) REFERENCES Curso (ID),
);

CREATE TABLE Area (
   ID INTEGER PRIMARY KEY NOT NULL UNIQUE,
   Nome VARCHAR(45) NOT NULL UNIQUE,
);

CREATE TABLE Curso (
   ID INTEGER PRIMARY KEY UNIQUE NOT NULL,
   Idioma VARCHAR(45),
   Autor VARCHAR(45),
   Conteudo VARCHAR(45),
   URL VARCHAR(45) NOT NULL,
   Titulo VARCHAR(45),
   Horas INTEGER,
   Avaliacao INTEGER,
   FOREIGN KEY (Area_ID) REFERENCES Area (ID),
);

CREATE TABLE Modulo (
   ID INTEGER PRIMARY KEY NOT NULL UNIQUE,
   Horas INTEGER,
   Nome VARCHAR(45),
   Topico VARCHAR(45),
   FOREIGN KEY (Curso_ID) REFERENCES Curso (ID),
);

CREATE TABLE Comentario (
   ID INTEGER PRIMARY KEY NOT NULL UNIQUE,
   Autor VARCHAR(45),
   Avaliacao VARCHAR(45),
   Conteudo VARCHAR(45),
   FOREIGN KEY (Modulo_ID) REFERENCES Modulo (ID),
   FOREIGN KEY (Modulo_Curso_ID) REFERENCES Curso (ID),
);

CREATE TABLE Video (
   ID INTEGER PRIMARY KEY NOT NULL UNIQUE,
   Titulo VARCHAR(45),
   URL VARCHAR(45),
   Duracao INTEGER,
   Descricao VARCHAR(45),
   FOREIGN KEY (Modulo_ID) REFERENCES Modulo (ID),
   FOREIGN KEY (Modulo_Curso_ID) REFERENCES Curso (ID),
);
